# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Vendasta Style Guide
tagline:          'Content style guide'
description:      'Content style guide for the ever growing marketing team of Vendasta'
url:              https://vendasta.github.io/content-style-guide/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
